/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pyFqlBUGsld
 */
import Featured from "@/components/blogs/featured";
import Latest from "@/components/blogs/latest";

export default function Blogs() {
    return (
        <div className="flex-1 py-6 bg-gray-100 dark:bg-gray-900 rounded-lg mx-6">
            <main className="flex-1 py-6">
                <Featured />
                <Latest />
            </main>
        </div>
    );
}
