/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pyFqlBUGsld
 */
import Featured from "@/components/blogs/featured"
import Latest from "@/components/blogs/latest"

export default function Blogs() {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1 py-6">
        <Featured />
        <Latest />
      </main>
    </div>
  )
}
