import patch from "@/lib/patch.json";

/**
 * The inline sprite: icons (24 × 24, 1.5 stroke, square caps), the Golden
 * Record ornaments and the mission patch (`#ar-patch`, generated by
 * scripts/generate-patch.mjs). It sits at the top of every page, rendered
 * once by the layout, so icons and the brand draw without JavaScript.
 * Use `<Icon name="arrow" />` and `<Patch />` (components/ui/icon.tsx).
 * Ported from the mockup's `svg#df-sprite` (_template.html).
 */
const SYMBOLS = [
    '<symbol id="i-arrow" viewBox="0 0 24 24"><path d="M4 12h15M13.5 6.5 19 12l-5.5 5.5"/></symbol>',
    '<symbol id="i-arrow-down" viewBox="0 0 24 24"><path d="M12 4v15M6.5 13.5 12 19l5.5-5.5"/></symbol>',
    '<symbol id="i-arrow-up" viewBox="0 0 24 24"><path d="M12 20V5M6.5 10.5 12 5l5.5 5.5"/></symbol>',
    '<symbol id="i-external" viewBox="0 0 24 24"><path d="M7 17 17 7M9 7h8v8"/></symbol>',
    '<symbol id="i-search" viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6"/><path d="m15 15 5 5"/></symbol>',
    '<symbol id="i-close" viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></symbol>',
    '<symbol id="i-menu" viewBox="0 0 24 24"><path d="M4 9h16M4 15h16"/></symbol>',
    '<symbol id="i-copy" viewBox="0 0 24 24"><path d="M8.5 8.5h11v11h-11z"/><path d="M15.5 8.5v-4h-11v11h4"/></symbol>',
    '<symbol id="i-check" viewBox="0 0 24 24"><path d="m5 12.5 4.5 4.5L19 7.5"/></symbol>',
    '<symbol id="i-rss" viewBox="0 0 24 24"><path d="M5 5a14 14 0 0 1 14 14M5 11a8 8 0 0 1 8 8"/><circle cx="6" cy="18" r="1.25" fill="currentColor" stroke="none"/></symbol>',
    '<symbol id="i-download" viewBox="0 0 24 24"><path d="M12 4v11M7 10.5l5 5 5-5M5 20h14"/></symbol>',
    '<symbol id="i-reset" viewBox="0 0 24 24"><path d="M5 12a7 7 0 1 0 2-4.9M5 4.5v3.5h3.5"/></symbol>',
    '<symbol id="i-pause" viewBox="0 0 24 24"><path d="M9 6v12M15 6v12"/></symbol>',
    '<symbol id="i-play" viewBox="0 0 24 24"><path d="M8 5.5 18.5 12 8 18.5z"/></symbol>',
    '<symbol id="i-print" viewBox="0 0 24 24"><path d="M7 9V4h10v5M4 9h16v7h-3M7 16H4M7 13.5h10V20H7z"/></symbol>',
    '<symbol id="i-share" viewBox="0 0 24 24"><path d="M12 15V4M7.5 8.5 12 4l4.5 4.5M5 12v8h14v-8"/></symbol>',
    '<symbol id="o-pulsar" viewBox="0 0 24 24"><path d="M12 12 3 5.5M12 12l9.5-4M12 12l10 3.5M12 12l6 9M12 12l-3 9.5M12 12 2 14.5M12 12 13.5 2M12 12 5 21M12 12l-8.5-1.5"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/></symbol>',
    '<symbol id="o-hydrogen" viewBox="0 0 24 24"><circle cx="6" cy="12" r="3.5"/><circle cx="18" cy="12" r="3.5"/><circle cx="6" cy="8.5" r=".9" fill="currentColor" stroke="none"/><circle cx="18" cy="15.5" r=".9" fill="currentColor" stroke="none"/><path d="M9.5 12h5M12 10v4"/></symbol>',
    '<symbol id="o-record" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="1.5"/><path d="M21 3 14.5 9.5"/></symbol>',
    '<symbol id="o-orbit" viewBox="0 0 24 24"><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(-18 12 12)"/><circle cx="12" cy="12" r="2.2" fill="currentColor" stroke="none"/><circle cx="20.6" cy="9.3" r="1.1" fill="currentColor" stroke="none"/></symbol>',
    '<symbol id="o-limb" viewBox="0 0 24 24"><path d="M1 19.5Q12 13 23 19.5"/><path d="M9.2 16.1a2.8 2.8 0 0 1 5.6 0" fill="currentColor" stroke="none"/></symbol>',
    '<symbol id="o-wave" viewBox="0 0 24 24"><path d="M1 12h3V7h2v10h2V4h2v16h2V8h2v8h2v-5h2v2h2v-1h2"/></symbol>',
    '<symbol id="o-dot" viewBox="0 0 24 24"><path d="M3 21 15 1M8 23 20 3" opacity=".5"/><circle cx="13.5" cy="12.5" r="1.4" fill="currentColor" stroke="none"/></symbol>',
    '<symbol id="o-star" viewBox="0 0 24 24"><path d="M12 3l1.6 7.4L21 12l-7.4 1.6L12 21l-1.6-7.4L3 12l7.4-1.6z" fill="currentColor" stroke="none"/></symbol>',
].join("");

export default function SvgSprite() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            className="df-sprite"
            aria-hidden="true"
            focusable="false"
            dangerouslySetInnerHTML={{ __html: SYMBOLS + patch.symbol }}
        />
    );
}
