import patch from "@/lib/patch.json";

/**
 * The inline sprite: icons (24 × 24, 1.5 stroke, square caps) and the
 * mission patch (`#ar-patch`, generated by
 * scripts/generate-patch.mjs). It sits at the top of every page, rendered
 * once by the layout, so icons and the brand draw without JavaScript.
 * Use `<Icon name="arrow" />` and `<Patch />` (components/ui/icon.tsx).
 * Ported from the mockup's `svg#df-sprite` (_template.html).
 */
const SYMBOLS = [
    '<symbol id="i-arrow" viewBox="0 0 24 24"><path d="M4 12h15M13.5 6.5 19 12l-5.5 5.5"/></symbol>',
    '<symbol id="i-arrow-down" viewBox="0 0 24 24"><path d="M12 4v15M6.5 13.5 12 19l5.5-5.5"/></symbol>',
    '<symbol id="i-arrow-up" viewBox="0 0 24 24"><path d="M12 20V5M6.5 10.5 12 5l5.5 5.5"/></symbol>',
    '<symbol id="i-external" viewBox="0 0 24 24"><path d="M7 17 17 7M9 7h8v8"/></symbol>',
    '<symbol id="i-search" viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6"/><path d="m15 15 5 5"/></symbol>',
    '<symbol id="i-close" viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></symbol>',
    '<symbol id="i-menu" viewBox="0 0 24 24"><path d="M4 9h16M4 15h16"/></symbol>',
    '<symbol id="i-copy" viewBox="0 0 24 24"><path d="M8.5 8.5h11v11h-11z"/><path d="M15.5 8.5v-4h-11v11h4"/></symbol>',
    '<symbol id="i-check" viewBox="0 0 24 24"><path d="m5 12.5 4.5 4.5L19 7.5"/></symbol>',
    '<symbol id="i-rss" viewBox="0 0 24 24"><path d="M5 5a14 14 0 0 1 14 14M5 11a8 8 0 0 1 8 8"/><circle cx="6" cy="18" r="1.25" fill="currentColor" stroke="none"/></symbol>',
    '<symbol id="i-download" viewBox="0 0 24 24"><path d="M12 4v11M7 10.5l5 5 5-5M5 20h14"/></symbol>',
    '<symbol id="i-reset" viewBox="0 0 24 24"><path d="M5 12a7 7 0 1 0 2-4.9M5 4.5v3.5h3.5"/></symbol>',
    '<symbol id="i-pause" viewBox="0 0 24 24"><path d="M9 6v12M15 6v12"/></symbol>',
    '<symbol id="i-play" viewBox="0 0 24 24"><path d="M8 5.5 18.5 12 8 18.5z"/></symbol>',
    '<symbol id="i-print" viewBox="0 0 24 24"><path d="M7 9V4h10v5M4 9h16v7h-3M7 16H4M7 13.5h10V20H7z"/></symbol>',
    '<symbol id="i-share" viewBox="0 0 24 24"><path d="M12 15V4M7.5 8.5 12 4l4.5 4.5M5 12v8h14v-8"/></symbol>',
    '<symbol id="i-theme" viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="M12 4a8 8 0 0 1 0 16z" fill="currentColor" stroke="none"/></symbol>',
].join("");

export default function SvgSprite() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            className="df-sprite"
            aria-hidden="true"
            focusable="false"
            dangerouslySetInnerHTML={{ __html: SYMBOLS + patch.symbol }}
        />
    );
}
